# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 425)
        MainWindow.setMinimumSize(QtCore.QSize(800, 425))
        MainWindow.setMaximumSize(QtCore.QSize(800, 425))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.from_drop_down = QtWidgets.QComboBox(self.centralwidget)
        self.from_drop_down.setGeometry(QtCore.QRect(130, 60, 101, 31))
        self.from_drop_down.setObjectName("from_drop_down")
        self.to_drop_down = QtWidgets.QComboBox(self.centralwidget)
        self.to_drop_down.setGeometry(QtCore.QRect(450, 60, 101, 31))
        self.to_drop_down.setObjectName("to_drop_down")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(134, 222, 91, 51))
        self.submit_button.setObjectName("submit_button")
        self.from_label = QtWidgets.QLabel(self.centralwidget)
        self.from_label.setGeometry(QtCore.QRect(80, 60, 41, 31))
        self.from_label.setObjectName("from_label")
        self.to_label = QtWidgets.QLabel(self.centralwidget)
        self.to_label.setGeometry(QtCore.QRect(410, 60, 31, 31))
        self.to_label.setObjectName("to_label")
        self.display_text = QtWidgets.QLabel(self.centralwidget)
        self.display_text.setGeometry(QtCore.QRect(280, 180, 491, 191))
        self.display_text.setText("")
        self.display_text.setObjectName("display_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.from_label.setText(_translate("MainWindow", "From:"))
        self.to_label.setText(_translate("MainWindow", "To:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
